apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlinebookstore
  template:
    metadata:
      labels:
        app: onlinebookstore
    spec:
      containers:
      - name: onlinebookstore
        image: onlinebookstore:latest
        ports:
        - containerPort: 8080