apiVersion: v1
kind: Service
metadata:
  name: onlinebookstore-service
spec:
  selector:
    app: onlinebookstore
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP